min_energy: 5
init_energy: 100
grass_energy: 15
idle_cost: 1
move_cost: 2
batch_size: 32

start_num_creatures: 6
start_grass_fraction: 0.3
start_rock_fraction: 0.05
start_water_fraction: 0.01
grass_grow_per_turn: 3
world_size: 60
scale: 10

view_distance: 2
steps_per_episode: 1000

layers: [24, 24]

