min_energy: 5
init_energy: 100
grass_energy: 5
idle_cost: 1
move_cost: 2
batch_size: 32

start_num_creatures: 6
start_num_wolves: 2
start_grass_fraction: 0.3
start_rock_fraction: 0.05
start_water_fraction: 0.01
grass_grow_per_turn: 3
world_size: 60
scale: 10

view_distance: 3
steps_per_episode: 1000
display_off: 1

layers: [16, 16]

